feat: restore from specific backup

diff --git a/private/check-config b/private/check-config
--- a/private/check-config
+++ b/private/check-config
@@ -3,21 +3,27 @@
 # check that config file exists
 config_path=$(dirname $0)/../.env
 if [[ ! -f "$config_path" ]]; then
-	echo "Could not find configuration file .env, exiting."
-	exit 11
+    echo "Could not find configuration file .env, exiting."
+    exit 11
 fi
 
 # include config file
 source $(dirname $0)/../.env
 
-# check path to site config param
-if [[ -z "$PATH_TO_SITE" ]]; then
-	echo "Missing configuration parameter PATH_TO_SITE, exiting."
-	exit 12
+# check project name
+if [[ -z "$PROJECT_NAME" ]]; then
+    echo "Missing configuration parameter PROJECT_NAME, exiting."
+    exit 12
 fi
 
-# check that project specified by PATH_TO_SITE exists
-if [[ ! -d "$PATH_TO_SITE" ]]; then
-	echo "Craft project at $PATH_TO_SITE not found, exiting."
-	exit 13
+# check path to site config param
+if [[ -z "$PROJECT_ROOT" ]]; then
+    echo "Missing configuration parameter PROJECT_ROOT, exiting."
+    exit 12
+fi
+
+# check that project specified by PROJECT_ROOT exists
+if [[ ! -d "$PROJECT_ROOT" ]]; then
+    echo "Craft project at $PROJECT_ROOT not found, exiting."
+    exit 13
 fi
diff --git a/restore-assets b/restore-assets
--- a/restore-assets
+++ b/restore-assets
@@ -2,8 +2,8 @@
 
 # check correct invocation
 if [[ "$#" -gt 1 ]]; then
-	echo "usage: restore-assets"
-	exit 1
+    echo "usage: restore-assets [archive-filename]"
+    exit 1
 fi
 
 # check config parameters common to all scripts
@@ -18,33 +18,30 @@ source $(dirname $0)/.env
 
 # check required storage parameters
 if [[ -z "$STORAGE_TYPE" || -z "$STORAGE_ROOT" ]]; then
-	echo "Missing storage configuration parameters, exiting."
-	echo "The following parameters are required: STORAGE_TYPE, STORAGE_ROOT"
-	exit 3
+    echo "Missing storage configuration parameters, exiting."
+    echo "The following parameters are required: STORAGE_TYPE, STORAGE_ROOT"
+    exit 3
 fi
 
-site_name="$(basename "$PATH_TO_SITE")"
+echo "Restoring assets of project $PROJECT_NAME."
 
-echo "Restoring assets of craft site $site_name."
-echo "Looking for most current backup..."
+if  [[ -z "$1" ]]; then
+    echo "Looking for most current backup..."
+    list_pattern="${STORAGE_ROOT}/*.tar.gz"
+else
+    echo "Looking for backup $1"
+    list_pattern="$1"
+fi
 
-list_pattern="${STORAGE_ROOT}/$site_name/*.tar.gz"
 list_cmd=$(dirname $0)/private/storage-list
 archive_url=$("$list_cmd" "$list_pattern" | tail -1)
 
 if [[ -z "$archive_url" ]]; then
-	echo "No assets backups found, exiting."
-	exit 4
+    echo "Asset backup(s) not found, exiting."
+    exit 4
 fi
 
 echo "Found $archive_url"
-read -r -p "Proceed? [Y/n] " response
-response_lowercase=$(echo $response | awk '{print tolower($0)}')
-if [[ $response_lowercase =~ ^(no|n)$ ]]
-then
-	echo "exiting"
-	exit 5
-fi
 
 temp_dir="$(mktemp -d)"
 
@@ -52,4 +49,4 @@ echo "Copying assets dump..."
 $(dirname $0)/private/storage-copy "$archive_url" "$temp_dir"
 
 echo "Restoring assets..."
-tar -xz -f "$temp_dir"/*.tar.gz -C "$PATH_TO_SITE"
+tar -xz -f "$temp_dir"/*.tar.gz -C "$PROJECT_ROOT"
diff --git a/set-perms b/set-perms
--- a/set-perms
+++ b/set-perms
@@ -1,9 +1,9 @@
 #! /usr/bin/env bash
 
 # check correct invocation
-if [[ "$#" -gt 1 ]]; then
-	echo "usage: set-perms"
-	exit 1
+if [[ "$#" -gt 0 ]]; then
+    echo "usage: set-perms"
+    exit 1
 fi
 
 # check config parameters common to all scripts
@@ -17,23 +17,29 @@ fi
 source $(dirname $0)/.env
 
 # check required file system parameters
-if [[ -z "$ASSETS_DIR" || -z "$FS_USER"  || -z "$FS_GROUP" ]]; then
-	echo "Missing file system configuration parameters, exiting."
-	echo "The following parameters are required: ASSETS_DIR, FS_USER, FS_GROUP"
-	exit 2
+if [[ -z "$FS_USER"  || -z "$FS_GROUP" ]]; then
+    echo "Missing file system configuration parameters, exiting."
+    echo "The following parameters are required: FS_USER, FS_GROUP"
+    exit 2
 fi
 
-local_writeable_dirs=(
+craft_writable_dirs=(
     "web/cpresources"
     "storage"
-    "$ASSETS_DIR"
 )
+
+if [[ -z "$ASSET_DIRS" ]]; then
+    writeable_dirs=("${craft_writable_dirs[@]}")
+else
+    writeable_dirs=("${craft_writable_dirs[@]}" "${ASSET_DIRS[@]}")
+fi
+
 writeable_dir_perms=775
 writeable_file_perms=664
 
-for dir in ${local_writeable_dirs[@]}
+for dir in ${writeable_dirs[@]}
 do
-    fullpath=${PATH_TO_SITE}/${dir}
+    fullpath=${PROJECT_ROOT}/${dir}
     if [[ -d "${fullpath}" ]] ; then
         echo "Fixing permissions for ${fullpath}"
         chown -R "$FS_USER":"$FS_GROUP" "${fullpath}"
